custom:
  serviceName: serverless-service-discovery-registry

service: ${self:custom.serviceName}

provider:
  name: aws
  runtime: nodejs12.x

functions:
  root:
    handler: handler.get
    events:
      - http:
          path: /
          method: get

